language: node_js

jobs:
  include:
    - os: linux
      dist: trusty
      node_js: 10

    - os: linux
      dist: trusty
      node_js: 12

    - os: linux
      dist: trusty
      node_js: 14

    - os: osx
      osx_image: xcode10.1
      node_js: 10

    - os: osx
      osx_image: xcode10.1
      node_js: 12

    - os: osx
      osx_image: xcode10.1
      node_js: 14
      
install:
  - npm ci

script:
  - npm run lint
