apps:
  # - script: "pipeline.js"
  #   name: "x5update_collect"
  #   cwd: "./preproc/dist/"
  #   args: "-tn uuid.update.material.collect -tp ../ontologies/update.material.collect"
  #   instances: 1,
  #   exec_mode: "fork"
  #   autorestart: true
  #   watch: false

  #   env:
  #     NODE_ENV: "development"
  #   env_production:
  #     NODE_ENV: "production"

  - script: "pipeline.js"
    name: "x5update_material_text_translation"
    cwd: "./preproc/dist/"
    args: "-tn uuid.update.material.text.translation -tp ../ontologies/update.material.text.translation"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false

    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"

  - script: "pipeline.js"
    name: "x5update_material_video_translation"
    cwd: "./preproc/dist/"
    args: "-tn uuid.update.material.video.translation -tp ../ontologies/update.material.video.translation"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false

    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"
