apps:
  - script: "pipeline.js"
    name: "X5update_collect"
    cwd: "./src/services/preproc/pipelines/"
    args: "-tn uuid.update.material.collect -tp ./ontologies/update.material.collect"
    instances: 1,
    exec_mode: "fork"
    autorestart: true
    watch: false

    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"

  - script: "pipeline.js"
    name: "X5update_material_text_translation"
    cwd: "./src/services/preproc/pipelines/"
    args: "-tn uuid.update.material.text.translation -tp ./ontologies/update.material.text.translation"
    instances: 2,
    exec_mode: "cluster"
    autorestart: true
    watch: false

    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"

  - script: "pipeline.js"
    name: "X5update_material_video_translation"
    cwd: "./src/services/preproc/pipelines/"
    args: "-tn uuid.update.material.video.translation -tp ./ontologies/update.material.video.translation"
    instances: 2,
    exec_mode: "cluster"
    autorestart: true
    watch: false

    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"
