apps:
  - script: "material-collector.js"
    name: "X5process_collect"
    cwd: "./src/services/preproc/"
    instances: 1,
    exec_mode: "fork"
    autorestart: true
    watch: false

    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"

  - script: "pipeline.js"
    name: "X5process_text_minimum"
    cwd: "./src/services/preproc/pipelines/"
    args: "-tn uuid.process.material.text.minimum -tp ./ontologies/process.material.text.minimum"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false

    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"

  - script: "pipeline.js"
    name: "X5process_text_translation"
    cwd: "./src/services/preproc/pipelines/"
    args: "-tn uuid.process.material.text.translation -tp ./ontologies/process.material.text.translation"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false

    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"

  - script: "pipeline.js"
    name: "X5process_video_translation"
    cwd: "./src/services/preproc/pipelines/"
    args: "-tn uuid.process.material.video.translation -tp ./ontologies/process.material.video.translation"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false

    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"