apps:
  - script: "material-collector.js"
    name: "x5process_collect"
    cwd: "./preproc/dist/"
    instances: 1,
    exec_mode: "fork"
    autorestart: true
    watch: false

    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"

  - script: "pipeline.js"
    name: "x5process_text_indexing"
    cwd: "./preproc/dist/"
    args: "-tn uuid.process.material.text.indexing -tp ../ontologies/process.material.text.indexing"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false

    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"

  - script: "pipeline.js"
    name: "x5process_text_translation"
    cwd: "./preproc/dist/"
    args: "-tn uuid.process.material.text.translation -tp ../ontologies/process.material.text.translation"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false

    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"

  - script: "pipeline.js"
    name: "x5process_video_translation"
    cwd: "./preproc/dist/"
    args: "-tn uuid.process.material.video.translation -tp ../ontologies/process.material.video.translation"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false

    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"