version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.7
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS_SEPARATOR: "$$'\n'"
      KAFKA_CREATE_TOPICS: |
        PROCESSING.MATERIAL.VIDEO:3:1
        PROCESSING.MATERIAL.TEXT:5:1
        STORING.MATERIAL.COMPLETE:5:1
        STORING.MATERIAL.PARTIAL:3:1
        STORING.RECSYS.TRANSITIONS:3:1
        STORING.RECSYS.SELECTIONS:3:1
        STORING.USERACTIVITY.CONNECT:3:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock